alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
alter table category_posts drop foreign key FK82w6sik5voqb8ysv5yxvi28wp;
alter table category_posts drop foreign key FKgjtl6hhu4h103nu9ec8btedp9;
alter table comment drop foreign key FKh1gtv412u19wcbx22177xbkjp;
alter table comment drop foreign key FK5yil4agwd52tq53twhip7bgi3;
alter table post drop foreign key FK12njtf8e0jmyb45lqfpt6ad89;
alter table post_categories drop foreign key FKikwnpibedlywpjo8wwkysf9p4;
alter table post_categories drop foreign key FKkutvrbjr0w20fuw5hen2w8uij;
alter table post_tags drop foreign key FKpoyg307ed2w6nbcthawvphds4;
alter table post_tags drop foreign key FKmmtgl185ka210lj8kenewllt1;
alter table tag_posts drop foreign key FKs0eay5et5drt4luxysesaw5lj;
alter table tag_posts drop foreign key FKkuuu0yw22k8dm6guqxvw269pb;
alter table user drop foreign key FK4cxhhgmvvauonk9h82sqdqnmf;
drop table if exists category;
drop table if exists category_posts;
drop table if exists comment;
drop table if exists permission;
drop table if exists post;
drop table if exists post_categories;
drop table if exists post_tags;
drop table if exists tag;
drop table if exists tag_posts;
drop table if exists user;
